---
title: "Programming Languages"
author: "Rahim Jutha"
date: "2023-03-26"
output: html_document
---

# Load Packages

Important Variables
- title
- type
- appeared
- number_of_users
- number_of_jobs

```{r}
library(tidyverse)
library(glue)
library(ggtext)
library(scales)
library(ggview)
library(showtext)
library(patchwork)
```

# Load Data

```{r}
data <- read_csv("data/languages.csv")
```
# Load Fonts

```{r}
font_add_google(name = "Roboto Condensed", family = "Roboto Condensed")
font_add_google(name = "Bebas Neue", family = "BebasNeue")
font_add_google("Oswald", family = "Oswald")
showtext_auto()
showtext_opts(dpi = 300)
```

# Pre-processing
```{r}
df <- 
  data %>%
  select(title, type, appeared, number_of_jobs, number_of_users) %>%
  filter(type == 'pl') %>%
  mutate(
    title = case_when(
      title == "Arduino Programming Language" ~ "Arudino",
      TRUE ~ title
    ),
    lab1 = 
      glue("<span style=font-size:16pt>**{title} - {appeared}**</span><br><span style=font-size:14pt>{comma(number_of_users)}</span>"),
    lab2 =
      glue("<span style=font-size:16pt>**{title} - {appeared}**</span><br><span style=font-size:14pt>{comma(number_of_jobs)}</span>"),
    color = case_when(
      title == "R" ~ "dark",
      TRUE ~ "light",
    )
  )
```


# Visualisation
```{r}
plot1 <- 
  df %>%
  arrange(-number_of_users) %>%
  slice_head(n=10) %>%
  ggplot(aes(x = number_of_users, y = fct_reorder(title, number_of_users))) +
  geom_col(aes(fill = color)) +
  geom_richtext(aes(label = lab1), hjust = "inward", fill = NA, label.colour = NA, lineheight = .9) +
  scale_fill_manual(values = c("#276DC2", "grey70")) +
  
  labs(
    title = "<span style=font-size:24pt;font-family:BebasNeue>Number of Users</span>",
    fill = NULL,
    x = NULL,
    y = NULL
  ) +
  
  guides(
    fill = "none"
  ) +
  
  theme_minimal(base_family = "Roboto Condensed") +
  theme(
    plot.background = element_rect(fill = "grey90", color = NA),
    plot.margin = margin(10,0,10,0),
    plot.title.position = "plot",
    
    plot.title = element_markdown(hjust = .5),
    
    axis.text = element_blank(),
    panel.grid = element_blank()
  )

ggview(units = "in", height = 7, width = 5)
```

```{r}
plot2 <- 
  df %>%
  arrange(-number_of_jobs) %>%
  slice_head(n=10) %>%
  ggplot(aes(x = number_of_jobs, y = fct_reorder(title, number_of_jobs))) +
  geom_col(aes(fill = color)) +
  geom_richtext(aes(label = lab2), hjust = "inward", fill = NA, label.colour= NA, lineheight = .9 ) +
  scale_fill_manual(values = c("#276DC2", "grey70")) +
  
  labs(
    title = "<span style=font-size:24pt;font-family:BebasNeue>Number of Jobs</span>",
    fill = NULL,
    x = NULL,
    y = NULL
  ) +
  
  guides(
    fill = "none"
  ) +
  
  theme_minimal(base_family = "Roboto Condensed") +
  theme(
    plot.background = element_rect(fill = "grey90", color =  NA),
    plot.margin = margin(10,0,10,0),
    plot.title.position = "plot",
    
    plot.title = element_markdown(hjust = .5),
    
    axis.text = element_blank(),
    panel.grid = element_blank()
  )

ggview(units = "in", height = 7, width = 5)
```

```{r}
plot1 + plot2 +
  plot_layout(ncol = 2) +
  plot_annotation(
    title = "<span style=font-size:30pt>*R cracks rop 10 programming languages for users & jobs*</span>",
    subtitle = "<span style=font-size:18pt>R is a programming language and software environment used for data analysis, statistical<br>computing, and graphics. It's open-source, popular among statisticians and data scientists,<br> and has a large collection of packages for handling and manipulating data, visualizing results,<br> and running statistical models.</span>",
    caption = "<span style=font-size:12pt>Filtered to only include programming languages (excluding Query/Markup Languages).<br>Graphic by Rahim Jutha | Source: _Programming Language Database_</span>",
    theme = theme(
      plot.background = element_rect(fill = "grey90", color = NA),
      panel.background = element_rect(fill = "#grey90", color = NA),
      
      plot.title = element_markdown(family = "Oswald", hjust = .5, margin = margin(t=10,b=10)),
      plot.caption = element_markdown(family = "Roboto Condensed"),
      plot.subtitle = element_markdown(family = "Roboto Condensed", margin = margin(t = 0, r=30,l=30, b = 10))
  )
    #   plot.title = element_text(family = "Bebas Neue", color = "#3E4C59", size = 125, hjust = 0.5, margin = margin(t = 10, b = 10)),
    #   plot.caption = element_text(family = "Roboto Condensed", color = "#3E4C59", size = 30, hjust = 0.5))
  )

ggview(units = "in", height = 8, width = 10)

ggsave("pl_plot.png", units = "in", height = 8, width = 10)
ggsave("pl_plot.svg", units = "in", height = 8, width = 10)
```
